<template>
  <section v-if="loading || villas.length" ref="sectionEl" class="home-villas" :class="{ visible }">
    <div v-if="loading" class="home-villas__shell home-villas__skeleton" aria-label="Loading villas"><div></div><div></div><div></div></div>
    <div v-else class="home-villas__shell">
      <div class="home-villas__copy">
        <span>{{ copy.eyebrow }}</span><h2>{{ copy.title }}</h2><p>{{ copy.description }}</p>
        <div class="home-villas__actions"><RouterLink :to="localizedPath('experiences')" class="home-villas__button home-villas__button--primary">{{ copy.explore }} <ArrowRight/></RouterLink><a :href="advisorHref" target="_blank" rel="noreferrer" class="home-villas__button">{{ copy.advisor }}</a></div>
      </div>
      <div class="home-villas__cards">
        <VillaCard :villa="villas[0]" large :label="copy.view" />
        <div class="home-villas__secondary"><VillaCard v-if="villas[1]" :villa="villas[1]" :label="copy.view"/><VillaCard v-if="villas[2]" :villa="villas[2]" :label="copy.view"/></div>
      </div>
    </div>
    <div v-if="!loading" class="home-villas__benefits"><span v-for="item in copy.benefits" :key="item"><Check/>{{item}}</span></div>
  </section>
</template>
<script setup>
import{computed,defineComponent,h,onBeforeUnmount,onMounted,ref}from'vue';import{ArrowRight,Check,MapPin}from'lucide-vue-next';import{RouterLink}from'vue-router';import{getFeaturedVillas}from'../services/villas.service';import{useLocalizedNavigation}from'../composables/useLocalizedNavigation';
const{locale,localizedPath}=useLocalizedNavigation();const villas=ref([]),loading=ref(true),visible=ref(false),sectionEl=ref(null);let observer;
const copy=computed(()=>locale.value==='es-mx'?{eyebrow:'Experiencias',title:'Ahora contamos con Villas.',description:'Complementa tu vuelo privado con una selección de villas, residencias vacacionales y experiencias cuidadosamente elegidas para hacer de tu viaje una experiencia completa.',explore:'Explorar Villas',advisor:'Hablar con un asesor',view:'Ver Villa',benefits:['Villas cuidadosamente seleccionadas','Atención personalizada','Privacidad durante toda tu estancia','Estancias en destinos exclusivos']}:{eyebrow:'Experiences',title:'We now offer Villas.',description:'Complement your private flight with a selection of villas, vacation residences and carefully curated experiences for a complete journey.',explore:'Explore Villas',advisor:'Speak with an advisor',view:'View Villa',benefits:['Carefully selected villas','Personalized assistance','Privacy throughout your stay','Stays in exclusive destinations']});
const advisorHref=computed(()=>`https://wa.me/525586186576?text=${encodeURIComponent(locale.value==='es-mx'?'Hola, quiero conocer las villas disponibles.':'Hello, I would like to explore the available villas.')}`);
const VillaCard=defineComponent({props:{villa:Object,large:Boolean,label:String},setup(p){return()=>p.villa?h(RouterLink,{to:`/${locale.value}/experiencias/${p.villa.slug}`,class:['home-villa-card',{'home-villa-card--large':p.large}]},{default:()=>[h('img',{src:p.villa.coverUrl,alt:p.villa.name,loading:'lazy',decoding:'async'}),h('div',{class:'home-villa-card__overlay'}),h('div',{class:'home-villa-card__content'},[h('span',[h(MapPin),p.villa.destination]),h('h3',p.villa.name),h('strong',[p.label,h(ArrowRight)])])] }):null}});
onMounted(async()=>{try{villas.value=await getFeaturedVillas(3)}catch{villas.value=[]}finally{loading.value=false;requestAnimationFrame(()=>{if(!sectionEl.value)return;observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)visible.value=true},{threshold:.12});observer.observe(sectionEl.value)})}});onBeforeUnmount(()=>observer?.disconnect());
</script>
<style scoped>
.home-villas{background:#fff;color:#102433;opacity:0;transform:translateY(18px);transition:opacity .4s,transform .4s}.home-villas.visible{opacity:1;transform:none}.home-villas__shell{width:min(1320px,calc(100% - 56px));margin:auto;padding:130px 0 90px;display:grid;grid-template-columns:.72fr 1.28fr;gap:75px;align-items:center}.home-villas__copy>span{color:#a57c36;text-transform:uppercase;letter-spacing:.2em;font-size:.66rem;font-weight:600}.home-villas__copy h2{font:500 clamp(3rem,5vw,5.2rem)/.98 'Playfair Display',serif;margin:20px 0}.home-villas__copy p{max-width:500px;color:#66747d;line-height:1.8}.home-villas__actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:30px}.home-villas__button{min-height:50px;padding:0 20px;display:flex;align-items:center;gap:10px;border:1px solid #b68c45;color:#102433;text-decoration:none;text-transform:uppercase;letter-spacing:.1em;font-size:.61rem;font-weight:600}.home-villas__button--primary{background:#071827;color:#fff;border-color:#071827}.home-villas__button svg{width:15px}.home-villas__cards{display:grid;grid-template-columns:1.35fr 1fr;gap:14px;height:610px}.home-villas__secondary{display:grid;grid-template-rows:1fr 1fr;gap:14px}.home-villas__cards :deep(.home-villa-card){position:relative;display:block;min-height:0;overflow:hidden;border-radius:12px;color:white}.home-villas__cards :deep(.home-villa-card img){width:100%;height:100%;object-fit:cover;transition:transform .3s}.home-villas__cards :deep(.home-villa-card:hover img){transform:scale(1.02)}.home-villas__cards :deep(.home-villa-card__overlay){position:absolute;inset:0;background:linear-gradient(0deg,rgba(4,16,27,.88),transparent 65%)}.home-villas__cards :deep(.home-villa-card__content){position:absolute;left:24px;right:24px;bottom:24px}.home-villas__cards :deep(.home-villa-card__content span){display:flex;gap:7px;align-items:center;font-size:.65rem;text-transform:uppercase;letter-spacing:.1em}.home-villas__cards :deep(.home-villa-card__content span svg){width:14px;color:#c9a35a}.home-villas__cards :deep(h3){font:500 1.65rem 'Playfair Display',serif;margin:9px 0}.home-villas__cards :deep(.home-villa-card--large h3){font-size:2.4rem}.home-villas__cards :deep(strong){display:flex;align-items:center;gap:8px;color:#d6b36c;text-transform:uppercase;font-size:.61rem;letter-spacing:.1em}.home-villas__cards :deep(strong svg){width:14px}.home-villas__benefits{min-height:105px;border-top:1px solid #ece8e2;display:grid;grid-template-columns:repeat(4,1fr);padding:0 max(28px,calc((100% - 1320px)/2))}.home-villas__benefits span{display:flex;align-items:center;justify-content:center;gap:10px;border-right:1px solid #ece8e2;font-size:.72rem}.home-villas__benefits span:last-child{border:0}.home-villas__benefits svg{width:18px;color:#b88c43}.home-villas__skeleton div{height:500px;background:#ece8e2;animation:pulse 1.2s infinite}.home-villas__skeleton div:first-child{height:250px}@keyframes pulse{50%{opacity:.5}}
@media(max-width:950px){.home-villas__shell{grid-template-columns:1fr}.home-villas__cards{height:580px}.home-villas__benefits{grid-template-columns:1fr 1fr}.home-villas__benefits span{min-height:70px}}@media(max-width:620px){.home-villas__shell{width:calc(100% - 30px);padding:90px 0 60px}.home-villas__cards{display:flex;height:430px;overflow-x:auto;scroll-snap-type:x mandatory;margin-right:-15px;padding-right:15px}.home-villas__secondary{display:contents}.home-villas__cards :deep(.home-villa-card){flex:0 0 87%;scroll-snap-align:start}.home-villas__benefits{grid-template-columns:1fr;padding:15px}.home-villas__benefits span{justify-content:flex-start;border:0;min-height:48px}}
</style>
